version: 2.1

jobs:
  build: 
    docker: 
      - image: cimg/base:2023.09
    steps:
      - setup_remote_docker: 
        version: 20.10.14
      - run: echo "Starting Build process"
      - run: docker build -t docker-react -f Dockerfile.dev .

workflows: 
  build_project:
    jobs:
      - build